# configuration for develop/CI branch

-
  branches:
    only:
      - dev
      - master

  skip_tags: true
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU

  pull_requests:
    do_not_increment_build_number: false

  install:
    - choco install gitversion.portable -pre -y

  before_build:
    - ps: cd src
    - ps: .paket\paket restore
    - ps: cd..
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo

  build:
    verbosity: minimal

  after_build:
    - ps: cd src
    - ps: .paket\paket pack --version $env:GitVersion_LegacySemVerPadded bin
    - ps: cd..

  cache:
    - src\packages -> **\packages.config
    # - '%USERPROFILE%\.nuget\packages -> **\project.json'

  artifacts:
    - path: \src\bin\MahApps.Metro.SimpleChildWindow.*.nupkg
    - path: \src\bin\Release\MahApps.Metro.SimpleChildWindow.Demo\
      name: MahApps.Metro.SimpleChildWindow.Demo.$(GitVersion_LegacySemVerPadded)
      type: zip
